name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  template:
    description: 'Template string or path to template file'
    required: true
  variables:
    description: 'Variables to substitute in the template'
    required: true

# Define your outputs here.
outputs:
  text:
    description: 'Rendered template string'

runs:
  using: node20
  main: dist/index.js
